### ISSUE TITLE
New OO fork completed

### ISSUE THREAD

**Issue by samtuke** [jonhurlock/Twitter-Application-Only-Authentication-OAuth-PHP#10]
Hey, I forked this and made it OO, added some basic unit tests. Not sure what you'd want to do about that; maybe link to it from your project page? It's not backwards compatible with your current script (no functions), but hopefully useful to others.

My fork is also available via composer thanks to a json file I added.

Repo: https://github.com/samtuke/Twitter-Application-Only-Authentication-OAuth-PHP

**Comment by jonhurlock** [comment]
Thanks, but i want to keep this example as simple as possible, and human readable. Though good work :+1:

**Comment by samtuke** [comment]
Fair enough. Shame my unit tests aren't separable from the code. Regardless of the lib logic itself I think tests are important.
