### ISSUE TITLE
Generalized API request

### ISSUE THREAD

**Issue by samyhajal** [jonhurlock/Twitter-Application-Only-Authentication-OAuth-PHP#11]
Added a function to send any request to the Twitter API. Must specify the bearer token, query name, response format and parameters of the request. See here: www.github.com/samyhajal/Twitter-Application-Only-Authentication-OAuth-PHP

**Comment by jonhurlock** [comment]
Nice work, I wanted to keep this example as simple as possible, but good implementation :+1: The search function was just used as an example.
