### ISSUE TITLE
It works only if I remove the "Content-Length" in the $headers array

### ISSUE THREAD

**Issue by nicocasel** [jonhurlock/Twitter-Application-Only-Authentication-OAuth-PHP#12]
Thanks for this very useful script.

However, in my case, it only works if I remove:
"Content-Length: 29" (line 37)

**Comment by jonhurlock** [comment]
Hi @nicocasel I was wondering, are you also using the code in line 45?

``` php
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials"); // post body/fields to be sent
```

The length of this data <em><b>grant_type=client_credentials</b></em> is 29 characters, that is why I have included this header in line 37.

Thanks for bringing this to my attention.

**Comment by nicocasel** [comment]
Yes, I am using the "grant_type" code line.
However, I think I had to remove the "Content-lenght" due to our proxy.

**Comment by jonhurlock** [comment]
@nicocasel ok thanks it seems that the content-length doesn't have to be there. So i will remove it. Thanks for the feedback.
