### ISSUE TITLE
Get error while trying to us statuses/home_timeline in place of search/tweets

### ISSUE THREAD

**Issue by geegirls3** [jonhurlock/Twitter-Application-Only-Authentication-OAuth-PHP#5]
This worked for me with search only. I'm trying to get timeline.
function get_home_timeline($bearer_token, $query, $result_type='mixed', $count='25'){
    $url = "https://api.twitter.com/1.1/statuses/home_timeline.json"; // base url
    $q = urlencode(trim($query)); // query term
    $formed_url ='?q='.$q; // fully formed url
    if($result_type!='mixed'){$formed_url = $formed_url.'&result_type='.$result_type;} // result type - mixed(default), recent, popular
    if($count!='15'){$formed_url = $formed_url.'&count='.$count;} // results per page - defaulted to 15
    $formed_url = $formed_url.'&include_entities=true'; // makes sure the entities are included, note @mentions are not included see documentation
    $headers = array( 
        "GET /1.1/statuses/home_timeline.json".$formed_url." HTTP/1.1", 
        "Host: api.twitter.com", 
        "User-Agent: GeeWebSolutions Twitter Application-only OAuth App v.1",
        "Authorization: Bearer ".$bearer_token."",
    );
    $ch = curl_init();  // setup a curl
    curl_setopt($ch, CURLOPT_URL,$url.$formed_url);  // set url to send to
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); // set custom headers
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // return output
    $retrievedhtml = curl_exec ($ch); // execute the curl
    curl_close($ch); // close the curl
    return $retrievedhtml;
}

/\* lets run a timeline.*/
$bearer_token = get_bearer_token(); // get the bearer token
print get_user_timeline($bearer_token, "GeeWebSolutions"); //  search for the work 'test'
invalidate_bearer_token($bearer_token);

Get this error.

{"errors":[{"message":"Your credentials do not allow access to this resource","code":220}]}

What am I doing wrong?

**Comment by jonhurlock** [comment]
The home_timeline request requires user context in terms of authentication (see the right hand side of this page https://dev.twitter.com/docs/api/1.1/get/statuses/home_timeline ) . So I don't believe you can do this using application only-authentication, instead you will have to us application user-authentication (see: https://dev.twitter.com/docs/auth/oauth#user-context ).

As well as this, there is no query parameter, so you couldn't pass GeeWebSolutions if you wanted to (Again look at valid parameters on https://dev.twitter.com/docs/api/1.1/get/statuses/home_timeline ) :wink:

**Comment by geegirls3** [comment]
Actually I'm testing this for a Dashboard that have 322 users.  That's why I wanted application-only authentication. 

Date: Mon, 1 Jul 2013 11:24:49 -0700
