### ISSUE TITLE
Application only tokens ???

### ISSUE THREAD

**Issue by geegirls3** [jonhurlock/Twitter-Application-Only-Authentication-OAuth-PHP#6]
I was told not to use the consumer key and secret created in my twitter dev app.  
Just to use the oauth_token and oauth_token_secret returned from the
oauth/access_token call instead.  Is this true?

**Comment by jonhurlock** [comment]
As mentioned previously you will have to use the signed Oauth authentication method, this is different to application-only authentication. See the relevant documents:

https://dev.twitter.com/docs/auth
https://dev.twitter.com/docs/auth/obtaining-access-tokens
https://dev.twitter.com/docs/auth/authorizing-request

The code in this repository will currently NOT allow you to access home_timeline

**Comment by geegirls3** [comment]
So I can't use application-only to authenticate multiple users via 1 application?  See this explanation.
Twitter offers applications the ability to issue authenticated requests on behalf of the application itself (as opposed to on behalf of a specific user). Twitter's implementation is based on the Client Credentials Grant flow of the OAuth 2 specification. Note that OAuth 1.0a is still required to issue requests on behalf of users.
Okay since I have an application (dashboard) with 312 twitter users.  I'm only grabbing the number of subscribers (followers) per user and displaying it with a widget.
So I'm confused by reading this and your answer saying I should use signed Oauth which is for 1 user not multiple users.
I'm conflicted.

Date: Mon, 1 Jul 2013 20:15:17 -0700
