### ISSUE TITLE
Empty response from twitter

### ISSUE THREAD

**Issue by rayiezhf** [jonhurlock/Twitter-Application-Only-Authentication-OAuth-PHP#7]
I am getting empty response in the curl_exec
$retrievedhtml = curl_exec ($ch); // execute the curl

There's no php errors or warnings..
can anybody tell me what can be the issue..?

**Comment by jonhurlock** [comment]
As you have posted a similar question on another repository I assume it is something to do with your credentials. Can you be more specific to which method/function you are calling that returns the empty response.

**Comment by chuchanpr** [comment]
The curl methods prints the output of the function and i get the empty result in $retrievedhtml = curl_exec ($ch);

**Comment by pmhou** [comment]
Experiencing the exact same issue too.

**Comment by PatchRanger** [comment]
In order to debug you should use this:

```
$response = curl_exec($ch);
if($response === false)
{
    echo 'Curl error #'.curl_errno($ch).': ' . curl_error($ch);
}
```

Source: http://terriswallow.com/weblog/2011/curl-local-wamp-empty-solved-facebook/
